#!/bin/bash
clang-format -i services/src/print_service_stub.cpp
clang-format -i services/src/print_bms_death_recipient.cpp
clang-format -i services/src/print_callback_proxy.cpp
clang-format -i services/src/print_extension_callback_proxy.cpp
clang-format -i services/src/print_bms_helper.cpp
clang-format -i services/src/print_service_ability.cpp
clang-format -i frameworks/innerkitsimpl/src/print_notify.cpp
clang-format -i frameworks/innerkitsimpl/src/print_extension_info.cpp
clang-format -i frameworks/innerkitsimpl/src/print_callback.cpp
clang-format -i frameworks/innerkitsimpl/src/printer_capability.cpp
clang-format -i frameworks/innerkitsimpl/src/print_callback_stub.cpp
clang-format -i frameworks/innerkitsimpl/src/printer_info.cpp
clang-format -i frameworks/innerkitsimpl/src/print_manager_client.cpp
clang-format -i frameworks/innerkitsimpl/src/print_sync_load_callback.cpp
clang-format -i frameworks/innerkitsimpl/src/napi_print_utils.cpp
clang-format -i frameworks/innerkitsimpl/src/print_extension_callback_stub.cpp
clang-format -i frameworks/innerkitsimpl/src/print_preview_attribute.cpp
clang-format -i frameworks/innerkitsimpl/src/print_margin.cpp
clang-format -i frameworks/innerkitsimpl/src/print_job.cpp
clang-format -i frameworks/innerkitsimpl/src/print_sa_death_recipient.cpp
clang-format -i frameworks/innerkitsimpl/src/print_range.cpp
clang-format -i frameworks/innerkitsimpl/src/print_page_size.cpp
clang-format -i frameworks/innerkitsimpl/src/print_resolution.cpp
clang-format -i frameworks/innerkitsimpl/src/print_service_proxy.cpp
clang-format -i frameworks/kits/extension/src/print_extension.cpp
clang-format -i frameworks/kits/extension/src/print_extension_context.cpp
clang-format -i frameworks/kits/extension/src/js_print_extension_context.cpp
clang-format -i frameworks/kits/extension/src/js_print_extension_connection.cpp
clang-format -i frameworks/kits/extension/src/js_print_callback.cpp
clang-format -i frameworks/kits/extension/src/js_print_extension.cpp
clang-format -i frameworks/kits/extension/src/print_extension_module_loader.cpp
clang-format -i interfaces/kits/jsnapi/extension/print_extension_module.cpp
clang-format -i interfaces/kits/jsnapi/extensionctx/print_extension_context_module.cpp
clang-format -i interfaces/kits/napi/src/print_task.cpp
clang-format -i interfaces/kits/napi/src/napi_print_task.cpp
clang-format -i interfaces/kits/napi/src/napi_print_ext.cpp
clang-format -i interfaces/kits/napi/src/napi_inner_print.cpp
clang-format -i interfaces/kits/napi/src/print_module.cpp
clang-format -i interfaces/kits/napi/src/print_async_call.cpp

clang-format -i services/include/print_service_ability.h
clang-format -i services/include/print_callback_proxy.h
clang-format -i services/include/print_bms_helper.h
clang-format -i services/include/print_bms_death_recipient.h
clang-format -i services/include/print_extension_callback_proxy.h
clang-format -i services/include/print_service_stub.h
clang-format -i utils/include/print_log.h
clang-format -i utils/include/print_constant.h
clang-format -i frameworks/innerkitsimpl/include/print_service_proxy.h
clang-format -i frameworks/innerkitsimpl/include/print_resolution.h
clang-format -i frameworks/innerkitsimpl/include/print_extension_info.h
clang-format -i frameworks/innerkitsimpl/include/print_range.h
clang-format -i frameworks/innerkitsimpl/include/print_job.h
clang-format -i frameworks/innerkitsimpl/include/print_page_size.h
clang-format -i frameworks/innerkitsimpl/include/print_manager_client.h
clang-format -i frameworks/innerkitsimpl/include/print_notify.h
clang-format -i frameworks/innerkitsimpl/include/print_sync_load_callback.h
clang-format -i frameworks/innerkitsimpl/include/iprint_callback.h
clang-format -i frameworks/innerkitsimpl/include/print_margin.h
clang-format -i frameworks/innerkitsimpl/include/print_preview_attribute.h
clang-format -i frameworks/innerkitsimpl/include/print_callback_stub.h
clang-format -i frameworks/innerkitsimpl/include/printer_capability.h
clang-format -i frameworks/innerkitsimpl/include/iprint_extension_callback.h
clang-format -i frameworks/innerkitsimpl/include/napi_print_utils.h
clang-format -i frameworks/innerkitsimpl/include/print_callback.h
clang-format -i frameworks/innerkitsimpl/include/print_extension_callback_stub.h
clang-format -i frameworks/innerkitsimpl/include/printer_info.h
clang-format -i frameworks/innerkitsimpl/include/iprint_service.h
clang-format -i frameworks/innerkitsimpl/include/print_sa_death_recipient.h
clang-format -i frameworks/kits/extension/include/print_extension_context.h
clang-format -i frameworks/kits/extension/include/js_print_extension_context.h
clang-format -i frameworks/kits/extension/include/js_print_extension_connection.h
clang-format -i frameworks/kits/extension/include/js_print_extension.h
clang-format -i frameworks/kits/extension/include/js_print_callback.h
clang-format -i frameworks/kits/extension/include/print_extension_module_loader.h
clang-format -i frameworks/kits/extension/include/print_extension.h
clang-format -i interfaces/kits/napi/include/napi_inner_print.h
clang-format -i interfaces/kits/napi/include/napi_print_task.h
clang-format -i interfaces/kits/napi/include/print_async_call.h
clang-format -i interfaces/kits/napi/include/napi_print_ext.h
clang-format -i interfaces/kits/napi/include/print_task.h
